version: 2
jobs:
  build:
    docker:
      # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/k-saka/slack-haven

    steps:
      - checkout
      - run: go get ./...
      - run: go get -u golang.org/x/lint/golint
      - run: make check
      - run: make test
